version: "3.8"
services:
  rag_app:
    image: stanislavlia/tiny_rag
    volumes:
      - ./rag_app/:/app/
    ports:
      - 8012:80

  chroma:
    image: chromadb/chroma
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    

volumes:
  index_data:
    driver: local
  backups:
    driver: local

