name: Build RAG app and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u stanislavlia --password-stdin

    - name: Build and push RAG app image to Docker Hub
      run: |
        docker buildx create --use
        docker buildx build \
          --tag stanislavlia/tiny_rag:latest \
          --push .
          ./rag_app/

    env:
      DOCKERHUB_USER: stanislavlia
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
