name: Build RAG app and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u stanislavlia --password-stdin

    - name: "Build app and push to DOCKERHUB"
      uses: docker/build-push-action@v5
      with:
        context: ./rag_app/
        file: ./rag_app/Dockerfile
        push: true
        tags: stanislavlia/tiny_rag:latest

    # - name: Build and push
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: .
    #       file: ./Dockerfile
    #       push: true
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest

    env:
      DOCKERHUB_USER: stanislavlia
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
