name: Build RAG app and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ DOCKERHUB_USER }} --password-stdin

    - name: Build and push RAG app image to Docker Hub
      run: docker buildx create --use docker buildx build \
            --file rag_app/Dockerfile \
            --tag stanislavlia/tiny_rag:latest \
            --push .

    env:
      DOCKERHUB_USER: stanislavlia
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
